#+TITLE: LOD-Laundromat
#+AUTHOR: Wouter Beek

* add URI

Adding a new URI to the seed list results in the following
registration:

#+BEGIN_SRC prolog
$(URI_HASH){relative: $(BOOL), status: added, uri: $(URI)}
#+END_SRC

We are storing seedlist registrations in a SWI dictionary
datastructure.  SWI dictionaries are very similar to the JSON format
for data exchange.  The main difference is the ~$(HASH)~, which we
will use to link seedlist registrations to one another.

The value of ~$(HASH)~ is computed in the following way:
  1. Take the value of ~$(URI)~
  2. Map uppercase characters that appear in the scheme or host
     components to their corresponding lowercase characters[fn::See
     §6.2.2.1 of RFC 3986
     (https://tools.ietf.org/html/rfc3986#section-6.2.2.1)].
  3. Map lowercase characters that denote hexadecimal digits within a
     percent-encoded octet to their corresponding uppercase
     characters[fn::See §6.2.2.1 of RFC 3986
     (https://tools.ietf.org/html/rfc3986#section-6.2.2.1)].
  4. Decode percent-encoded octets that denote unreserved
     characters[fn::See §6.2.2.2 of RFC 3986
     (https://tools.ietf.org/html/rfc3986#section-6.2.2.1)].
  5. Remove the relative path references ~.~ and ~..~ by applying
     reference resolution[fn::See §6.2.2.3 of RFC 3986
     (https://tools.ietf.org/html/rfc3986#section-6.2.2.3)].
  6. Take the MD5 hash.

We allow relative URIs to be added to the seedlist, denoted by the
Boolean property ~relative~.  We cannot do anything useful with
relative URIs, because their download location is unknown due to a
missing host machine name.  Still, we want to be able to quantify how
often a dataset is erroneously denoted by a relative URI.

The ~status~ property is going to keep track of the URI throughout the
data cleaning process.  Its initial state is ~added~, which means that
it is added to the seedlist.

The ~uri~ property stores the URI itself.

* download URI
This state takes seeds that match the pattern in (1), and changes them
to match pattern (2) during the download process.  If the download
fails we only have metadata ~$(HTTP_META)~ about the TCP and/or HTTP
communication process, resulting in a seed record with pattern (3).
If the download succeeds, there is also content metadata
~$(CONTENT_META)~, resulting in a seed record with pattern (4).

#+BEGIN_SRC prolog
[1] $(URI_HASH){relative: false, status: added, uri: $(URI)}
[2] $(URI_HASH){relative: false, status: downloading, uri: $(URI)}
[3] $(URI_HASH){http: $(HTTP_META), relative: false, status: failed, uri: $(URI)}
[4] $(URI_HASH){content: $(CONTENT_META), http: $(HTTP_META), relative: false, status: filed, uri: $(URI)}
#+END_SRC

~$(HTTP_META)~ has the following form:

#+BEGIN_SRC prolog
http{
  headers: $(HTTP_HEADERS),
  status: $(STATUS_CODE),
  uri: $(URI),
  version: version{major: $(NONNEG), minor: $(NONNEG)},
  walltime: $(FLOAT)
}
#+END_SRC

~$(CONTENT_META)~ has the following form:

#+BEGIN_SRC prolog
$(CONTENT_HASH){
  newline: $(NEWLINE),
  number_of_bytes: $(NONNEG),
  number_of_chars: $(NONNEG),
  number_of_lines: $(NONNEG)
}
#+END_SRC

* unpack URI
This state is started for each seed that matches [1].  If the seed
denotes a downloaded file that is an archive, the resulting seed
record will include pointer to each directly included ‘child’ file as
in [3].  Status ~depleted~ denotes that no more files are enclosed
within this file.  For each child, a new seed record of the form [4]
is added to the seedlist.

If the seed denotes a downloaded file that contains data, its seed
record is updated to have status ~unarchived~.  We must determine the
character encoding of the data file in order to be able to read it.
Unfortunately, this can only be determined heuristically.  We perform
the following steps:
  1. We look for a Unicode Byte Order Marker (BOM), which indicates
     that the file has Unicode encoding.
  2. If not BOM is present, we use /unchardet/ in order to guess the
     encoding.  If the encoding is incompatible with Unicode[fn::An
     example of a common encoding that is compatible with Unicode is
     (US-)ASCII.], we recode the entire file using /iconv/.

#+BEGIN_SRC prolog
[1] $(HASH){status: filed}
[2] $(HASH){status: unarchiving}
[3] $(HASH){children: $(CHILD_HASHES), status: depleted}
[4] $(CHILD_HASH){
      archive: $(ARCHIVE_META),
      content: $(CONTENT_META),
      parent: $(PARENT_HASH),
      status: filed
    }
[5] $(HASH){status: unarchived}
#+END_SRC

* guess Media Type
#+BEGIN_SRC prolog
[1] $(HASH){status: unarchived}
[2] $(HASH){status: guessing}
[3] $(HASH){format: $(FORMAT), status: guessed}
#+END_SRC

~$(FORMAT)~ is one of the following values:
  1. JSON-LD
  2. N-Quads
  3. N-Triples
  4. RDF/XML
  5. RDFa
  6. TriG
  7. Turtle

* parse RDF
#+BEGIN_SRC prolog
[1] $(HASH){format: $(FORMAT), status: guessed}
[2] $(HASH){status: parsing}
[3] $(CLEAN_HASH){
      content: $(CONTENT_META),
      dirty: $(HASH),
      status: cleaned
    }
[4] $(HASH){status: parsed}
#+END_SRC

* detect literal errors
