prefix ll: <https://lodlaundromat.org/def/>
select ?label {
  {
    select (sum(?n) as ?n) {
      ?s ll:numberOfQuadruples|ll:numberOfTriples ?n .
    }
  }
  bind(replace(?n,"[0-9](?=(?:[0-9]{3})+(?![0-9]))","$0.") as ?label)
}
